# Site wide configuration

title:            Nirav Gandhi's Blog
locale:           en_US
url:              http://niyando.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Nirav Gandhi
  avatar: niravgandhi.jpg
  bio: "Codes, Creates, Cleans, Cooks, Cheers & Cares.<br><br>Senior Product Developer at F22 Labs, India"
  email: ndgandhi.88@gmail.com
  disqus-shortname:
  twitter: niyando
  facebook: niyando
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: niyando
  stackoverflow: http://stackoverflow.com/users/1278007/nirav-gandhi
  linkedin: ndgandhi
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
